### LOGIN
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

### SIGNUP
POST http://localhost:8000/api/auth/signup
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123",
  "password_confirm": "admin123"
}

### get
GET http://localhost:8000/api/auth/user